#include "header.h"

void pumpMvOff()
{
    GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, 0); //Pump
    GPIOPinWrite(GPIO_PORTK_BASE, GPIO_PIN_5, 0); //LED Pump
    GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, 0); //MV1
    GPIOPinWrite(GPIO_PORTN_BASE, GPIO_PIN_1, 0); //LED MV1
    GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, 0); //MV2
    GPIOPinWrite(GPIO_PORTN_BASE, GPIO_PIN_0, 0); //LED MV2
    GPIOPinWrite(GPIO_PORTG_BASE, GPIO_PIN_0, 0); //MV3
    GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_4, 0); //LED MV3
    GPIOPinWrite(GPIO_PORTL_BASE, GPIO_PIN_4, 0); //MV4
    GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_0, 0); //LED MV4
}

void pumpOn()
{
    GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_1, GPIO_PIN_1); //Pump
    GPIOPinWrite(GPIO_PORTK_BASE, GPIO_PIN_5, GPIO_PIN_5); //LED Pump
}

void mv1On()
{
    GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_2, GPIO_PIN_2); //MV1
    GPIOPinWrite(GPIO_PORTN_BASE, GPIO_PIN_1, GPIO_PIN_1); //LED MV1
}

void mv2On()
{
    GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_3, GPIO_PIN_3); //MV2
    GPIOPinWrite(GPIO_PORTN_BASE, GPIO_PIN_0, GPIO_PIN_0); //LED MV2
}

void mv3On()
{
    GPIOPinWrite(GPIO_PORTG_BASE, GPIO_PIN_0, GPIO_PIN_0); //MV3
    GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_4, GPIO_PIN_4); //LED MV3
}

void mv4On()
{
    GPIOPinWrite(GPIO_PORTL_BASE, GPIO_PIN_4, GPIO_PIN_4); //MV4
    GPIOPinWrite(GPIO_PORTF_BASE, GPIO_PIN_0, GPIO_PIN_0); //LED MV4
}
